# Shiny app regression example


This README file is the supporting documentation accompagning this Shiny application. 

### 1. Instructions given for this project

1. Write a shiny application with associated supporting documentation. The documentation should be thought of as whatever a user will need to get started using your application. 
2. Deploy the application on Rstudio's shiny server.
3. Share the application link by pasting it into the text box below. 
4. Share your server.R and ui.R code on github. 

The application must include the following:

1. Some form of input (widget: textbox, radio button, checkbox, ...).
2. Some operation on the ui input in sever.R.
3. Some reactive output displayed as a result of server calculations.
4. You must also include enough documentation so that a novice user could use your application.
5. The documentation should be at the Shiny website itself. Do not post to an external link.

The Shiny application in question is entirely up to you. However, if you're having trouble coming up with ideas, you could start from the simple prediction algorithm done in class and build a new algorithm on one of the R datasets packages. Please make the package simple for the end user, so that they don't need a lot of your prerequisite knowledge to evaluate your application. You should emphasize a simple project given the short time frame.  

### 2. Description of this Shiny application

This Shiny application shows a regression example on car speed and its stopping distance  as well as how transformation of the input and output affect the regression model.

This app contains 3 checkbox and several subselect input controlling the values:


Transformation of Y          To take transformation of y variable(stopping distance)
Transformation of X          To take transformation of x variable(car speed)
Fit a curve to the data      Fit a line on the plot
    Log                      Take log transformation
    Square Root              Take square root transformation
95% Confidence Interval      Fit a 95% confidence interval range besides the line
  

### 3. Directives on how to visualize this Shiny application

Option 1: Direct link: click [here](http://lincrampton.shinyapps.io/time2retire/)

Option 2: Download the `server.R` and `ui.R` files and place them in a directory named 'time2retire'. Open an R session and set the working directory to the folder that contains the directory 'time2retire'. Then run the following commands:

```
library(shiny)
runApp('time2retire')
```
